### signUp

POST http://localhost:3000/v1/api/shop/signUpasdsa
Content-Type: application/json
x-api-key: a1f42561c29e2a27fd2640c9216ac9eb9f9aca4f28633975ddf3fe2bb32d164b19f52a0e9ebfdab810b1d607aab0cd3598377fed4e2b947a1adeac44cc4b2707

{
    "name" : "Shops Test",
    "email" : "chien@gmail.com",
    "password": "password"
}